# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler
#' @description A Gibbs sampler using Rcpp in Chapter 9 exercise 9.8
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @param a the parameter of bivariate density
#' @param b the parameter of bivariate density
#' @param n the number of experiments
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100,10,2,1,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(N, thin, a, b, n) {
    .Call('_StatComp21016_gibbsC', PACKAGE = 'StatComp21016', N, thin, a, b, n)
}

